config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'dashboard#index'
  
  resource :dashboard do
    resources :usuarios
    resources :produtos
    resources :pedidos
    resources :itens
    resources :contas
    resources :transacoes
    resources :receitas
    resources :utilizacoes
  end
end

app/models/BaixaEstoque.rb
class BaixaEstoque < ActiveRecord::Base
  self.table_name = "BaixaEstoques"
end

app/models/Conta.rb
class Conta < ActiveRecord::Base
  self.table_name = "Conta"
  
  validates :duracao, presence: true
  validates :numeroMesa, presence: true
  validates :qtdClientes, presence: true
  
  def to_s
    return "Mesa: #{self.numeroMesa}"
  end
end

app/models/Estoque.rb
class Estoque < ActiveRecord::Base
  self.table_name = "Estoque"
  
  validates :qtdItem, presence: true
  validates :produto_id, presence: true
  
  def get_produto
    Produto.find self.produto_id
  end
  
  def to_s
    self.try(:get_produto).try(:nome)
  end
end

app/models/Item.rb
class Item < ActiveRecord::Base
  self.table_name = "Item"
  
  validates :nome, uniqueness: true, presence: true
  validates :limiar, presence: true
  validates :prazo_validade, presence: true
end

app/models/Pedido.rb
class Pedido < ActiveRecord::Base
  self.table_name = "Pedido"
  
  validates :conta, presence: true
  validates :produto, presence: true

  def get_conta
    Conta.find self.conta
  end
  
  def get_produto
    Produto.find self.produto
  end
end

app/models/Produto.rb
class Produto < ActiveRecord::Base
  self.table_name = "Produto"
  
  # has_many :items, :foreign_key => "player_alias"
  
  validates :nome, uniqueness: true, presence: true
  
  def to_s
    self.nome
  end
end

app/models/Receita.rb
class Receita < ActiveRecord::Base
  self.table_name = "Receitas"
end

app/models/Transacao.rb
class Transacao < ActiveRecord::Base
  self.table_name = "Transacao"
end

app/models/Usuario.rb
class Usuario < ActiveRecord::Base
  self.table_name = "Usuarios"
  
  validates :login, uniqueness: true
  validates :email, uniqueness: true
end

app/models/Utilizacoes.rb
class Utilizacoes < ActiveRecord::Base
  self.table_name = "Utilizacoes"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_create :create_usuario
  
private
  
  def create_usuario
    Usuario.create(login: self.login, password: SecureRandom.hex, admin: false)
  end
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/helpers/transacoes_helper.rb
module TransacoesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>AVidaEBela</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <script
  src="https://code.jquery.com/jquery-3.1.1.min.js"
  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
  crossorigin="anonymous"></script>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

<body>
    <div class="container">
        <%= render "shared/header" %>

        <%= yield %>
        
        <%= render "shared/footer" %>
    </div>
</body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
    
    <div class="container-fluid">
        <div class="navbar-header">
            
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <%= link_to root_url do %>
                <%= image_tag "logo_transp.png", width: 128, height: 50, id: "logo" %>
            <% end %>
            
            <!-- <%= link_to "A Vida é Bela", root_url, class: "navbar-brand" %> -->
        </div>
        
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><%= link_to "Dashboard", root_url %></li>
                
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gerenciar <span class="caret"></span></a>
                    
                    <ul class="dropdown-menu">
                        <li><%= link_to "Produtos", dashboard_produtos_path %></li>
                        <li><%= link_to "Contas", dashboard_contas_path %></li>
                        <li><%= link_to "Pedidos", dashboard_pedidos_path %></li>
                        <li><%= link_to "Itens", dashboard_itens_path %></li>
                        <li><%= link_to "Usuários", dashboard_usuarios_path %></li>
                        
                        <li role="separator" class="divider"></li>
                        
                        <li><%= link_to "Transações", dashboard_transacoes_path %></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "Receitas", dashboard_receitas_path %></li>
                    </ul>
                </li>
            </ul>
            
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="...">
                </div>
                <button type="submit" class="btn btn-default">Buscar</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <% if current_user %>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.try(:login) %> <span class="caret"></span></a>
                        
                        <ul class="dropdown-menu">
                            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                <% else %>
                    <li><%= link_to "Acessar", new_user_session_path %></li>
                <% end %>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>