config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'dashboard#index'
  
  resource :dashboard do
    resources :usuarios
    resources :produtos
    resources :pedidos
    resources :itens
    resources :contas
    resources :transacoes
    resources :receitas
    resources :utilizacoes
  end
end

app/models/BaixaEstoque.rb
class BaixaEstoque < ActiveRecord::Base
  self.table_name = "BaixaEstoques"
end

app/models/Conta.rb
class Conta < ActiveRecord::Base
  self.table_name = "Conta"
  
  validates :duracao, presence: true
  validates :numeroMesa, presence: true
  validates :qtdClientes, presence: true
  
  def to_s
    return "Mesa: #{self.numeroMesa}"
  end
end

app/models/Estoque.rb
class Estoque < ActiveRecord::Base
  self.table_name = "Estoque"
  
  validates :qtdItem, presence: true
  validates :produto_id, presence: true
  
  def get_produto
    Produto.find self.produto_id
  end
  
  def to_s
    self.try(:get_produto).try(:nome)
  end
end

app/models/Item.rb
class Item < ActiveRecord::Base
  self.table_name = "Item"
  
  validates :nome, uniqueness: true, presence: true
  validates :limiar, presence: true
  validates :prazo_validade, presence: true
end

app/models/Pedido.rb
class Pedido < ActiveRecord::Base
  self.table_name = "Pedido"
  
  validates :conta, presence: true
  validates :produto, presence: true

  def get_conta
    Conta.find self.conta
  end
  
  def get_produto
    Produto.find self.produto
  end
end

app/models/Produto.rb
class Produto < ActiveRecord::Base
  self.table_name = "Produto"
  
  # has_many :items, :foreign_key => "player_alias"
  
  validates :nome, uniqueness: true, presence: true
  
  def to_s
    self.nome
  end
end

app/models/Receita.rb
class Receita < ActiveRecord::Base
  self.table_name = "Receitas"
end

app/models/Transacao.rb
class Transacao < ActiveRecord::Base
  self.table_name = "Transacao"
end

app/models/Usuario.rb
class Usuario < ActiveRecord::Base
  self.table_name = "Usuarios"
  
  validates :login, uniqueness: true
  validates :email, uniqueness: true
end

app/models/Utilizacoes.rb
class Utilizacoes < ActiveRecord::Base
  self.table_name = "Utilizacoes"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_create :create_usuario
  
private
  
  def create_usuario
    Usuario.create(login: self.login, password: SecureRandom.hex, admin: false)
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :authenticate_user!

  def index
    @pedidos = Pedido.all
    @pedido = Pedido.new
  end

  def show
    @pedido = Pedido.find params[:id]
  end

  def new
    @pedido = Pedido.new
  end

  def update
  end

  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to dashboard_pedido_url(@pedido), notice: 'Pedidoo was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
  end
  
private 

def pedido_params
  params.require(:pedido).permit(:observacao, :conta, :produto)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/helpers/transacoes_helper.rb
module TransacoesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/utilizacoes_helper.rb
module UtilizacoesHelper
end

app/views/pedidos/create.html.erb
<h1>Pedidos#create</h1>
<p>Find me in app/views/pedidos/create.html.erb</p>

app/views/pedidos/delete.html.erb
<h1>Pedidos#delete</h1>
<p>Find me in app/views/pedidos/delete.html.erb</p>

app/views/pedidos/index.html.erb
<div class="page-header">
    <h1 style="margin-left:40%">Pedidos</h1>
</div>

<!-- <div class="row">
    <div class="col-lg-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Filtrar por...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Filtrar</button>
            </span>
        </div>
    </div>
</div> -->

<div class="row" style="margin-top:50px">
    <div class="col-md-5">
        <div class="list-group">
            <% @pedidos.each do |pedido| %>
                <%= link_to "#{pedido.id} - Mesa #{pedido.get_conta.try(:id)}", dashboard_pedido_path(pedido), class: "list-group-item" %>
            <% end %>
        </div>
    </div>

    <div class="col-md-7" id="product-actions">
        <div class="row">
            <div class="btn-group btn-group-lg" role="group">
                <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-adicionar">Adicionar Pedido
                </button>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="modal-adicionar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Adicionar Pedido</h4>
          </div>
           
              <%= form_for(@pedido, url: dashboard_pedidos_path, html: { class: "col-md-6" }) do |f| %>
                <% if @pedido.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

                    <ul>
                    <% @pedido.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                
                <div class="form-group">
                  <%= f.label :observacao, "Observação" %>
                  <%= f.text_area :observacao, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :produto, "Produto" %>
                  <%= f.select :produto, options_for_select(Produto.all.collect{ |u| [u.nome, u.id] }), class: "form-control" %>
                </div>
                
                <div class="form-group">
                  <%= f.label :conta, "Conta" %>
                  <%= f.select :conta, options_for_select(Conta.all.collect{ |u| [u, u.id] }), class: "form-control" %>
                </div>
                
                <div class="actions">
                  <%= f.submit "Salvar", class: "btn btn-success" %>
                </div>
              <% end %>

          <!-- </div> -->
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>

</div>

app/views/pedidos/new.html.erb
<h1>Pedidos#new</h1>
<p>Find me in app/views/pedidos/new.html.erb</p>

app/views/pedidos/show.html.erb
<div class="well">
    <div class="media">
        <div class="media-left">
            <%= image_tag "item_placeholder.svg", class: "media-object", style: "width: 128px; height: 128px;" %>
        </div>
        <div class="media-body">
            <h4>Mesa <%= @pedido.get_conta.numeroMesa %></h4>
            <h3>Produto <%= @pedido.try(:get_produto).try(:nome) %></h3>
            <p>Observação <%= @pedido.observacao %></p>
            
            <p>
                <span class="label label-success">
                    <%= number_to_currency @pedido.try(:get_produto).try(:preco), unit: "R$" %>
                </span>
            </p>
            
            <p>Cadastrado em <%= @pedido.criado_em.strftime("%d/%m/%Y") %></p>
            <p>Atualizado em <%= @pedido.atualizado_em.strftime("%d/%m/%Y") %></p>
        </div>
    </div>
</div>

app/views/pedidos/update.html.erb
<h1>Pedidos#update</h1>
<p>Find me in app/views/pedidos/update.html.erb</p>