config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  root 'dashboard#index'
  
  resource :dashboard do
    resources :usuarios
    resources :produtos
    resources :pedidos
    resources :itens
    resources :contas
    resources :transacoes
    resources :receitas
    resources :utilizacoes
  end
end

app/models/BaixaEstoque.rb
class BaixaEstoque < ActiveRecord::Base
  self.table_name = "BaixaEstoques"
end

app/models/Conta.rb
class Conta < ActiveRecord::Base
  self.table_name = "Conta"
  
  validates :duracao, presence: true
  validates :numeroMesa, presence: true
  validates :qtdClientes, presence: true
  
  def to_s
    return "Mesa: #{self.numeroMesa}"
  end
end

app/models/Estoque.rb
class Estoque < ActiveRecord::Base
  self.table_name = "Estoque"
  
  validates :qtdItem, presence: true
  validates :produto_id, presence: true
  
  def get_produto
    Produto.find self.produto_id
  end
  
  def to_s
    self.try(:get_produto).try(:nome)
  end
end

app/models/Item.rb
class Item < ActiveRecord::Base
  self.table_name = "Item"
  
  validates :nome, uniqueness: true, presence: true
  validates :limiar, presence: true
  validates :prazo_validade, presence: true
end

app/models/Pedido.rb
class Pedido < ActiveRecord::Base
  self.table_name = "Pedido"
  
  validates :conta, presence: true
  validates :produto, presence: true

  def get_conta
    Conta.find self.conta
  end
  
  def get_produto
    Produto.find self.produto
  end
end

app/models/Produto.rb
class Produto < ActiveRecord::Base
  self.table_name = "Produto"
  
  # has_many :items, :foreign_key => "player_alias"
  
  validates :nome, uniqueness: true, presence: true
  
  def to_s
    self.nome
  end
end

app/models/Receita.rb
class Receita < ActiveRecord::Base
  self.table_name = "Receitas"
end

app/models/Transacao.rb
class Transacao < ActiveRecord::Base
  self.table_name = "Transacao"
end

app/models/Usuario.rb
class Usuario < ActiveRecord::Base
  self.table_name = "Usuarios"
  
  validates :login, uniqueness: true
  validates :email, uniqueness: true
end

app/models/Utilizacoes.rb
class Utilizacoes < ActiveRecord::Base
  self.table_name = "Utilizacoes"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  after_create :create_usuario
  
private
  
  def create_usuario
    Usuario.create(login: self.login, password: SecureRandom.hex, admin: false)
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  def index
    @produtos = Produto.all
    @produto = Produto.new
  end

  def show
    @produto = Produto.find params[:id]
  end

  def create
    @produto = Produto.new(produto_params)
    
    p "inspecionar"
    p produto_params

    respond_to do |format|
      if @produto.save
        format.html { redirect_to dashboard_produto_url(@produto), notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  def new
    @produto = Produto.new
  end

  def update
  end

  def destroy
    @produto.destroy
    
    
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :preco)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/itens_helper.rb
module ItensHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/receitas_helper.rb
module ReceitasHelper
end

app/helpers/transacoes_helper.rb
module TransacoesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/helpers/utilizacoes_helper.rb
module UtilizacoesHelper
end

app/views/produtos/_form.html.erb
<%= form_for(produto, url: dashboard_produtos_path, html: { class: "col-md-6" }) do |f| %>
    <h2 class="lead">Adicionar produto</h2>
  <% if produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :nome, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :descricao %>
    <%= f.text_area :descricao, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :preco %>
    <%= f.text_field :preco, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Salvar", class: "btn btn-success" %>
  </div>
<% end %>

app/views/produtos/create.html.erb
<h1>Produtos#create</h1>
<p>Find me in app/views/produtos/create.html.erb</p>

app/views/produtos/delete.html.erb
<h1>Produtos#delete</h1>
<p>Find me in app/views/produtos/delete.html.erb</p>

app/views/produtos/index.html.erb
<div class="page-header">
    <h1 style="margin-left:40%">Produtos</h1>
</div>

<!-- <div class="row pesq">
    <div class="col-lg-6">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Filtrar por...">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Filtrar</button>
            </span>
        </div>
    </div>
</div> -->

<div class="row pesq" style="margin-top:50px">
    <div class="col-md-5">
        <div class="list-group">
            <% @produtos.each do |produto| %>
                <%= link_to produto.nome, dashboard_produto_path(produto), class: "list-group-item" %>
            <% end %>
        </div>
    </div>

    <div class="col-md-7" id="product-actions">
        <div class="row">
            <div class="btn-group btn-group-lg" role="group">
                <button type="button" class="btn btn-default btn btn-mesa" data-toggle="modal" data-target="#modal-adicionar">Adicionar Produto
                </button>
            </div>
        </div>
    </div>
    
    <div class="modal fade" id="modal-adicionar" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Adicionar produto</h4>
          </div>
           
              <%= form_for(@produto, url: dashboard_produtos_path, html: { class: "col-md-6" }) do |f| %>
                <% if @produto.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

                    <ul>
                    <% @produto.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                    </ul>
                  </div>
                <% end %>
                
                <div class="form-group">
                  <%= f.label :nome, "Nome" %>
                  <%= f.text_field :nome, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :descricao, "Descrição" %>
                  <%= f.text_area :descricao, class: "form-control" %>
                </div>
                
                <div class="form-group">
                    <%= f.label :preco, "Preço" %>
                    
                    <div class="input-group">
                        <div class="input-group-addon">$</div>
                        
                        <%= f.text_field :preco, class: "form-control", placeholder: "Preço" %>
                        
                        <div class="input-group-addon">.00</div>
                    </div>
                </div>

                <div class="actions">
                  <%= f.submit "Salvar", class: "btn btn-success" %>
                </div>
              <% end %>

          <!-- </div> -->
          <div class="modal-footer">
          </div>
        </div>
      </div>
    </div>

</div>

app/views/produtos/new.html.erb
<%= render 'form', produto: @produto %>

app/views/produtos/show.html.erb
<div class="well">
    <h2><%= @produto.nome %></h2>
    
    <p>
        Preço
        <span class="label label-success">
            <%= number_to_currency @produto.preco, unit: "R$" %>
        </span>
    </p>
    
    <p>Cadastrado em <%= @produto.criado_em.strftime("%d/%m/%Y") %></p>
    <p>Atualizado em <%= @produto.atualizado_em.strftime("%d/%m/%Y") %></p>
    
    <!-- <button type="button" class="btn btn-danger">Remover</button> -->
    
    <%= link_to 'Remover', dashboard_produto_url(@produto), method: :delete, class: "btn btn-danger", data: { confirm: 'Tem certeza?' } %>
</div>

app/views/produtos/update.html.erb
<h1>Produtos#update</h1>
<p>Find me in app/views/produtos/update.html.erb</p>